### PR TITLE
Maven install documentation added

### LINKED ISSUE #26: Archetype does not exist for version 1.0.0
When trying to create an adapter as described [here](https://github.com/IKOR-GmbH/sip-framework/blob/develop/docs/archetype.md), one gets an error message that the archetype does not exist:
```
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.2.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
[WARNING] The POM for de.ikor.sip.foundation:sip-archetype:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.502 s
[INFO] Finished at: 2021-12-05T14:23:22+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (de.ikor.sip.foundation:sip-archetype:1.0.0) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Input was the example from the documentation page:
```
mvn archetype:generate -DarchetypeGroupId=de.ikor.sip.foundation -DarchetypeArtifactId=sip-archetype -DarchetypeVersion=1.0.0 -DgroupId=de.ikor.sip.adapter -DartifactId=demo -DprojectName=DemoAdapter -Dversion=1.0.0-SNAPSHOT
```

### PR DESCRIPTION
**Pull request by vladiIkor**
# Description

Documentation updated with instructions how to clone project and install local artifacts before executing archetype command.

Fixes # 26

## Type of change

Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- Delete everything from \.m2\repository\de\ikor\sip directory
- Execute all commands described added with this PR
- Run archetype command with version 1.0.0
- Expected: archetype generates new adapter

# Checklist:
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing (regression) unit tests pass locally with my changes

### CODE REVIEW

**Comment by stieglma** [comment]
@vladiIkor we have the same issues with the docs in `archetype.md` maybe we want to only mention its usage in one location, if not then it has to be fixed in the other place, too

**Comment by vladiIkor** [comment]
> @vladiIkor we have the same issues with the docs in `archetype.md` maybe we want to only mention its usage in one location, if not then it has to be fixed in the other place, too

Thanks @stieglma 
Your comment makes sense. 
However, I still wouldn't copy this entry because it's not strictly related to archetype, but for all other SIP artifacts as well. Also it is not about archetype usage but about how to get wanted artifact. I think that installation.md is perfect location for such entry.
Plus, it's a temporary measurement and copying would just make it harder to maintain.

Would you agree?

**Comment by stieglma** [comment]
> > @vladiIkor we have the same issues with the docs in `archetype.md` maybe we want to only mention its usage in one location, if not then it has to be fixed in the other place, too
> 
> Thanks @stieglma Your comment makes sense. However, I still wouldn't copy this entry because it's not strictly related to archetype, but for all other SIP artifacts as well. Also it is not about archetype usage but about how to get wanted artifact. I think that installation.md is perfect location for such entry. Plus, it's a temporary measurement and copying would just make it harder to maintain.
> 
> Would you agree?

I had a closer look again, and I think I don't agree, IMHO on the installation page there should be a link to the archetype page, and the details should be there. At the moment the installation page basically only contains information about system requirements and archetype. 

Also I think that the installation page should additionally contain information what to do, if the archetype is not / cannot be used. But I wouldn't do that on this PR and rather in a new one.

**Comment by stieglma** [comment]
@vladiIkor we just got all the approvals and access to maven central. Version 1.0.0 is now deplyoed there, too: https://repo1.maven.org/maven2/de/ikor/sip/foundation/
So I guess documentation should just be updated to not have duplicates, but referring to github packages is no longer necessary

**Comment by vladiIkor** [comment]
SIP artifacts are now available on maven central

**Pull request closed without merging**
